### ISSUE TITLE
Unknown error occurred when adding a license plate

### ISSUE THREAD

**Issue by Sjeff** [eelcohn/home-assistant-rdw#32]
#### Versions
_RDW component version:_ Latest v2.9.8<br> 
_Home Assistant version:_ 0.114.4<br>
_Home Assistant platform: Home Assistant Supervised (Docker)_<br>

#### Expected behavior
Adding a new license plate entity and the sensors

#### Actual behavior
Tell us what happens instead
When adding a new license plate a unknows error occured:
![image](https://user-images.githubusercontent.com/11430228/93172414-1e2ad780-f72b-11ea-88d5-722c892bb05e.png)

#### Steps to reproduce
_1._ Add a new license plate<br>

#### Component log
Home Assistant Logs:

Log Details (ERROR)
Logger: aiohttp.server
Source: custom_components/rdw/config_flow.py:101
First occurred: 8:07:30 AM (3 occurrences)
Last logged: 8:10:47 AM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/real_ip.py", line 39, in real_ip_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 73, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 145, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 153, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 201, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/rdw/config_flow.py", line 101, in async_step_user
    config_entry = {'data', user_input}
TypeError: unhashable type: 'dict'
```

**Comment by eelcohn** [comment]
I'll try to look into this as soon as possible.

**Comment by groenmarsmannetje** [comment]
Just upgraded to latest RDW component version and I experience the same issue.

**Comment by Sjeff** [comment]
Hi,
@groenmarsmannetje install [v2.9.6](https://github.com/eelcohn/home-assistant-rdw/tree/v2.9.6) as this version does works.
then add your cars and update the manifest.json with the version number so you dont get the warning on startup:
```
{
	"codeowners": ["@eelcohn"],
	"config_flow": true,
	"dependencies": [],
	"documentation": "https://www.home-assistant.io/integrations/rdw",
	"domain": "rdw",
	"name": "RDW",
	"requirements": ["sodapy==2.0.0"],
	"version": "2.9.7"
}
```

**Comment by groenmarsmannetje** [comment]
Nope... I will not do this kind of workarounds. Will wait on new fixed version or otherwise remove it from my installation.

**Comment by Theoreet** [comment]
![image](https://user-images.githubusercontent.com/27493457/137157667-7fd1d2bc-abea-4b4a-b22b-46eb8162a1ef.png)
same error / problem

**Comment by TheRedBull205** [comment]
RDW has been build into HA version: 2021.12
https://rc--home-assistant-docs.netlify.app/integrations/rdw/
Beta release notes: https://rc--home-assistant-docs.netlify.app/blog/

(THANKS Frenck!!)

**Comment by eelcohn** [comment]
The RDW service was integrated in Home Assistant 2021.12, which makes my custom RDW integration obsolete. Please remove the custom RDW integration, and use the built-in RDW integration.
